// Do not remove or edit this file. Automatically generated by the Node.js Toolkit to host this
// application. It loads the application's own entry point (index.js) under Phusion Passenger.
//
// Passenger patches http.Server.prototype.listen before loading this file, so the application's
// listen() call binds to the Passenger-provided socket regardless of any hardcoded port.
require("./index.js");
